### ISSUE TITLE
Dick needs to approve the Electron

### ISSUE THREAD

**Issue by brandoaire** [spark/electron#22]
@jenesaisdiq this one is all you :+1:

**Comment by jenesaisdiq** [comment]
Is this just some kind of ceremonial honor? What part of the Electron?

**Comment by mohitbhoite** [comment]
ALL of it. The atom.

**Comment by jenesaisdiq** [comment]
If I don't approve of the subatomic particle, will our universe wink out?

**Comment by zsup** [comment]
that is uncertain.

**Comment by brandoaire** [comment]
The next revision of the Electron will be a release candidate.  We need you to look at the current version and provide feedback on any cosmetic or user issues that you notice

**Comment by technobly** [comment]
Several versions ahead now...
