### ISSUE TITLE
Current SIM Card holder part doesn't create reliable connection

### ISSUE THREAD

**Issue by brandoaire** [spark/electron#3]
Going to test the "tighter" version of the Kaweei SIM card slot part first, then can consider GCT part as higher cost alternate.  @jenesaisdiq will ship the parts to @technobly on 7/29

**Comment by technobly** [comment]
Tested the 2nd more snug sample, and it's a dang nice sim card holder!  All the problems with the previous one not allowing the card to fully insert are resolved with this one.  And the contacts are smooth and snug.
