### ISSUE TITLE
Confusing Silkscreen

### ISSUE THREAD

**Issue by brandoaire** [spark/electron#35]
We've received feedback from beta testers that the silkscreen markings are confusing, since they lie in between pins.  Potential solutions:
- adding a small triangular arrow pointing up or down next to the label?

**Comment by monkbroc** [comment]
Another reason for the confusion is that some labels are "above" the pin (VIN, 3V3) while most are "below".

**Comment by brandoaire** [comment]
Hey @monkbroc that specific issue has been fixed in subsequent versions of the hardware.

**Comment by monkbroc** [comment]
:+1: @brandoaire

**Comment by technobly** [comment]
I literally spent 60 seconds making this so please forgive me!  But what about just a blob of silkscreen that helps to tie the label to the pin above it?  Arrows would be hard to see... but this might work.
![2015-09-24_15-12-33](https://cloud.githubusercontent.com/assets/2249224/10087043/5bcc0a48-62d7-11e5-893a-d7b8ddb06a6f.png)

**Comment by monkbroc** [comment]
That would be good. I would have understood that intuitively.

**Comment by kennethlimcp** [comment]
I just realized the headers are labeled on the inside. Can we have them shown outside instead?

**Comment by jenesaisdiq** [comment]
Obviously a manufacturing error, @kennethlimcp. Won't be like that in production.

**Comment by technobly** [comment]
You've Cat 2 B Kitten Me!!! WAT.  I knew we were working on this and scratch tested samples.  I've been developing with 2 production Beta Electrons and have not noticed those labels until RIGHT MEOW.  :joy_cat:

**Comment by kennethlimcp** [comment]
This might be a good resolution in addition to a silkscreen improvement :)

**Comment by monkbroc** [comment]
That is bananas! I've never see that done before! I thought about labels on the side of the headers but didn't realize it could actually be done :smile: 

Yeah, consider this issue closed! (just make sure the labels are on all pins instead of just some)

**Comment by brandoaire** [comment]
Awww we were hoping to keep this as a surprise :-) don't tell!

**Comment by technobly** [comment]
Shred the files, shred the files!!

**Comment by kennethlimcp** [comment]
:fire: :rabbit: gone!

**Comment by mohitbhoite** [comment]
closing this issue now, header labels FTW
