### ISSUE TITLE
Consider reducing R13/14

### ISSUE THREAD

**Issue by andyw-lala** [spark/electron#38]
10K is high even for 3.3V @ 400KHz.

Recommend 4.7K or 3.6K for increased margin.

**Comment by monkbroc** [comment]
This is I2C, right? I believe the max rise time allowed is 1us so 4.7K or less sound correct.

**Comment by mohitbhoite** [comment]
I agree, 10K seems high at 400K. The datasheet schematic example uses 10K. This app note was useful: http://www.ti.com/lit/an/slva689/slva689.pdf

**Comment by mohitbhoite** [comment]
updated design to use 4K7
