### ISSUE TITLE
Feature request: Put modem in standby without sleeping MCU 

### ISSUE THREAD

**Issue by JDSymington** [spark/electron#45]
On some of the sleep modes available for the electron it is possible to set the SLEEP_NETWORK_STANDBY  flag. This will put the modem in standby mode before putting the MCU to sleep.

It would be really handy to put the modem in standby mode but keep the MCU active. This would drastically reduce power consumption and when data is ready to be sent a connection to the operator can quickly be made.

**Comment by kennethlimcp** [comment]
The better place to raise this up is probably at https://github.com/particle-iot/firmware

**Comment by JDSymington** [comment]
Will do thanks!
