### ISSUE TITLE
Consolidate passive package sizes

### ISSUE THREAD

**Issue by brandoaire** [spark/electron#6]
There are a bunch of passives that have both 0603 and 0402 components of the same value.  We can simplify our BOM by consolidating to a single package size.

**Comment by brandoaire** [comment]
<img width="434" alt="screenshot 2015-07-29 13 45 21" src="https://cloud.githubusercontent.com/assets/4020511/8965222/118f4d34-35f8-11e5-8f92-aadc5c7a0ab1.png">

**Comment by satishgn** [comment]
0603 footprint is used for certain parts since they are directly connected across high voltage/current 3.8V/3.3V regulator & fuel gauge ICs and using 0402 footprint without sufficient rating could be an issue. Let's discuss tonight and take a decision on this issue.
